"""
Chain Discovery Models.

Purpose: Data models for chain discovery context and decisions
Role: Structured data for failure analysis and LLM chain generation
Dependencies: pydantic
"""

from pydantic import BaseModel, Field


class ChainDiscoveryContext(BaseModel):
    """
    Extracted intelligence for chain discovery.

    Contains actionable signals from attack failures to guide
    intelligent converter chain generation.
    """

    defense_signals: list[str] = Field(
        default_factory=list,
        description="Defense mechanisms detected (e.g., 'keyword_filter', 'pattern_matching')"
    )
    failure_root_cause: str = Field(
        default="unknown",
        description="Primary reason why chains failed"
    )
    defense_evolution: str = Field(
        default="none",
        description="How defenses have adapted across iterations"
    )
    converter_effectiveness: dict[str, float] = Field(
        default_factory=dict,
        description="Historical success rates keyed by converter chain tuple string"
    )
    unexplored_directions: list[str] = Field(
        default_factory=list,
        description="New converter strategies worth trying"
    )
    required_properties: list[str] = Field(
        default_factory=list,
        description="Properties the next chain should have"
    )
    iteration_count: int = Field(
        default=0,
        description="Number of iterations completed"
    )
    best_score_achieved: float = Field(
        default=0.0,
        description="Highest score achieved so far"
    )
    best_chain_so_far: list[str] = Field(
        default_factory=list,
        description="Chain that achieved the best score"
    )


class ConverterChainCandidate(BaseModel):
    """
    Single converter chain candidate with metadata.

    Generated by ChainDiscoveryAgent for evaluation.
    """

    converters: list[str] = Field(
        description="Ordered list of converter names to apply"
    )
    expected_effectiveness: float = Field(
        ge=0.0,
        le=1.0,
        description="Predicted success probability (0-1)"
    )
    defense_bypass_strategy: str = Field(
        description="How this chain addresses detected defenses"
    )
    converter_interactions: str = Field(
        description="How the converters work together synergistically"
    )


class ChainDiscoveryDecision(BaseModel):
    """
    LLM-generated chain discovery decision.

    Contains multiple chain candidates with reasoning for selection.
    """

    chains: list[ConverterChainCandidate] = Field(
        min_length=1,
        max_length=5,
        description="Generated chain candidates (1-5)"
    )
    reasoning: str = Field(
        description="Overall reasoning for generated chains"
    )
    primary_defense_target: str = Field(
        description="Main defense mechanism being targeted"
    )
    exploration_vs_exploitation: str = Field(
        description="Whether focusing on exploring new strategies or exploiting known successes"
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Overall confidence in the chain selection (0-1)"
    )


class ChainSelectionResult(BaseModel):
    """
    Result of chain selection with full observability.

    Captures the entire selection process for debugging and analysis.
    """

    selected_chain: list[str] = Field(
        description="The final selected converter chain"
    )
    selection_method: str = Field(
        description="How the chain was selected (defense_match, highest_confidence, fallback)"
    )
    selection_reasoning: str = Field(
        description="Detailed explanation of why this chain was selected"
    )
    all_candidates: list[dict] = Field(
        default_factory=list,
        description="All candidate chains with their scores and rankings"
    )
    defense_match_details: dict = Field(
        default_factory=dict,
        description="Details about defense signal matching"
    )
    rejected_chains: list[dict] = Field(
        default_factory=list,
        description="Chains that were rejected and why"
    )
